
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    env_file:
      - ./neo4j/.env
    ports:
      - "7687:7687"
    volumes:
      - ./neo4j/init:/init
      - knowledge_base:/data
    entrypoint: ["/bin/bash","/init/init.sh"]
    networks:
      app_net:

networks:
  app_net:

volumes:
  knowledge_base: